backend:
  name: git-gateway
  branch: main # Change this to your default branch

media_folder: "public/uploads" # Where uploaded files will be stored
public_folder: "/uploads" # Path to access uploaded files

collections:
  - name: "pages"
    label: "Pages"
    folder: "src/pages" # Adjust according to your project
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
