backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "cms/_posts/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    description: >
      Add posts about recent activities, news, and stories related to your mission. Add posts about recent activities, news, and stories related to your mission.
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Author",
          name: "author",
          widget: "relation",
          collection: "authors",
          display_fields: [display_name],
          search_fields: [display_name],
          value_field: "name",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "events"
    label: "Events"
    folder: "cms/_events/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    description: >
      List upcoming events. Make sure to provide all necessary details for attendees.
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Event Date", name: "date", widget: "datetime" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "File", name: "file", widget: "file" }

  - name: "authors"
    label: "Authors"
    folder: "cms/_authors/"
    create: true
    editor:
      preview: false
    description: >
      Create profiles for team members who contribute content. Include their roles, backgrounds, and any relevant expertise.
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "author" }
      - { label: "Short Name", name: "name", widget: "string" }
      - { label: "Display Name", name: "display_name", widget: "string" }
      - { label: "Position", name: "position", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "about us"
    label: "About Us"
    description: >
      Edit content of your organization's mission, values, and history. Help visitors understand our purpose and goals.
    files:
      - label: "About MMF"
        name: "about mmf"
        file: "cms/_about_us/about_mmf.md"
        editor:
          preview: false
        fields:
          - { label: "Title", name: "title", widget: "string", required: true }
          - { label: "Body", name: "body", widget: "markdown", required: true }
      - label: "Our History"
        name: "our history"
        file: "cms/_about_us/our_history.md"
        editor:
          preview: false
        fields:
          - { label: "Title", name: "title", widget: "string", required: true }
          - { label: "Body", name: "body", widget: "markdown", required: true }
      - label: "The Employees"
        name: "the employees"
        file: "cms/_about_us/the_employees.md"
        editor:
          preview: false
        create: true
        fields:
          - { label: "Name", name: "name", widget: "string", required: true }
          - {
              label: "Position",
              name: "position",
              widget: "string",
              required: true,
            }
          - { label: "Bio", name: "bio", widget: "markdown", required: true }
          - {
              label: "Cover Image",
              name: "image",
              widget: "image",
              required: true,
            }

  - name: "support us"
    label: "Support Us"
    description: >
      Edit how people can donate or support your organization. Include information on the impact of their contributions and ways to get involved.
    files:
      - label: "Where do we get funds from"
        name: "funds"
        file: "cms/_support_us/funds.md"
        editor:
          preview: false
        fields:
          - { label: "Title", name: "title", widget: "string", required: true }
          - { label: "Body", name: "body", widget: "markdown", required: true }
      - label: "Ways to support"
        name: "ways to support"
        file: "cms/_support_us/ways_to_support.md"
        editor:
          preview: false
        fields:
          - { label: "Title", name: "title", widget: "string", required: true }
          - { label: "Body", name: "body", widget: "markdown", required: true }
      - label: "Volunteer"
        name: "volunteer"
        file: "cms/_support_us/volunteer.md"
        editor:
          preview: false
        fields:
          - { label: "Title", name: "title", widget: "string", required: true }
          - { label: "Body", name: "body", widget: "markdown", required: true }

  - name: "contact us"
    label: "Contact Us"
    folder: "cms/_contact_us"
    create: true
    description: >
      Edit essential contact details and a form for inquiries. Ensure visitors know how to reach you for questions or support.
    fields:
      - {
          label: "Role",
          name: "role",
          widget: "string",
          required: true,
          hint: "Example Leader Madagascar",
        }
      - { label: "Name", name: "name", widget: "string", required: true }
      - { label: "Email", name: "email", widget: "string", required: true }
      - { label: "Phone Number", name: "phone number", widget: "string" }

  - name: "our work"
    label: "Our Work"
    description: >
      Edit the projects and initiatives you are currently working on.
    files:
      - label: "Health Care"
        name: "health care"
        file: "cms/_our_work/health_care.md"
        editor:
          preview: false
        fields:
          - { label: "Title", name: "title", widget: "string", required: true }
          - { label: "Body", name: "body", widget: "markdown", required: true }
      - label: "Schooling"
        name: "schooling"
        file: "cms/_our_work/schooling.md"
        editor:
          preview: false
        fields:
          - { label: "Title", name: "title", widget: "string", required: true }
          - { label: "Body", name: "body", widget: "markdown", required: true }
      - label: "The Housing Situation"
        name: "the housing situation"
        file: "cms/_our_work/housing_situation.md"
        editor:
          preview: false
        fields:
          - { label: "Title", name: "title", widget: "string", required: true }
          - { label: "Body", name: "body", widget: "markdown", required: true }
      - label: "Nutrition"
        name: "nutrition"
        file: "cms/_our_work/nutrition.md"
        editor:
          preview: false
        fields:
          - { label: "Title", name: "title", widget: "string", required: true }
          - { label: "Body", name: "body", widget: "markdown", required: true }
      - label: "Music Lessons"
        name: "music lessons"
        file: "cms/_our_work/music_lessons.md"
        editor:
          preview: false
        fields:
          - { label: "Title", name: "title", widget: "string", required: true }
          - { label: "Body", name: "body", widget: "markdown", required: true }
      - label: "Cooperation with the Children"
        name: "cooperation with the children"
        file: "cms/_our_work/cooperation_children.md"
        editor:
          preview: false
        fields:
          - { label: "Title", name: "title", widget: "string", required: true }
          - { label: "Body", name: "body", widget: "markdown", required: true }
      - label: "Activities"
        name: "activities"
        file: "cms/_our_work/activities.md"
        editor:
          preview: false
        fields:
          - { label: "Title", name: "title", widget: "string", required: true }
          - { label: "Body", name: "body", widget: "markdown", required: true }
      - label: "Goals for the Future"
        name: "goals for the future"
        file: "cms/_our_work/future_goals.md"
        editor:
          preview: false
        fields:
          - { label: "Title", name: "title", widget: "string", required: true }
          - { label: "Body", name: "body", widget: "markdown", required: true }

  - name: "gallery"
    label: "Gallery"
    create: false
    description: >
      Upload photos and videos from our events and projects. Use this space to visually share our story and impact.
    files:
      - label: "Gallery"
        name: "gallery"
        file: "cms/_gallery/gallery.md"
        fields:
          - {
              label: "Images",
              name: "images",
              widget: "image",
              choose_url: true,
              media_library: { config: { multiple: true, max_files: 999 } },
            }
