backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "cms/_posts/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Author",
          name: "author",
          widget: "relation",
          collection: "authors",
          display_fields: [display_name],
          search_fields: [display_name],
          value_field: "name",
        }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "events"
    label: "Events"
    folder: "cms/_events/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Event Date", name: "date", widget: "datetime" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "authors"
    label: "Authors"
    folder: "cms/_authors/"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "author" }
      - { label: "Short Name", name: "name", widget: "string" }
      - { label: "Display Name", name: "display_name", widget: "string" }
      - { label: "Position", name: "position", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "about us"
    label: "About Us"
    files:
      - label: "About MMF"
        name: "about mmf"
        file: "cms/_about_us/about_mmf.md"
        editor:
          preview: false
        fields:
          - { label: "Title", name: "title", widget: "string", required: true }
          - { label: "Body", name: "body", widget: "markdown", required: true }
      - label: "Our History"
        name: "our history"
        file: "cms/_about_us/our_history.md"
        editor:
          preview: false
        fields:
          - { label: "Title", name: "title", widget: "string", required: true }
          - { label: "Body", name: "body", widget: "markdown", required: true }
      - label: "The Employees"
        name: "the employees"
        file: "cms/_about_us/the_employees.md"
        editor:
          preview: false
        create: true
        fields:
          - { label: "Name", name: "name", widget: "string", required: true }
          - {
              label: "Position",
              name: "position",
              widget: "string",
              required: true,
            }
          - { label: "Bio", name: "bio", widget: "markdown", required: true }
          - {
              label: "Cover Image",
              name: "image",
              widget: "image",
              required: true,
            }
  - name: "support us"
    label: "Support Us"
    files:
      - label: "Where do we get funds from"
        name: "funds"
        file: "cms/_support_us/funds.md"
        editor:
          preview: false
        fields:
          - { label: "Title", name: "title", widget: "string", required: true }
          - { label: "Body", name: "body", widget: "markdown", required: true }
      - label: "Ways to support"
        name: "ways to support"
        file: "cms/_support_us/ways_to_support.md"
        editor:
          preview: false
        fields:
          - { label: "Title", name: "title", widget: "string", required: true }
          - { label: "Body", name: "body", widget: "markdown", required: true }
      - label: "Volunteer"
        name: "volunteer"
        file: "cms/_support_us/volunteer.md"
        editor:
          preview: false
        fields:
          - { label: "Title", name: "title", widget: "string", required: true }
          - { label: "Body", name: "body", widget: "markdown", required: true }

  - name: "contact us"
    label: "Contact Us"
    folder: "cms/_contact_us"
    create: true
    fields:
      - {
          label: "Role",
          name: "role",
          widget: "string",
          required: true,
          hint: "Example Leader Madagascar",
        }
      - { label: "Name", name: "name", widget: "string", required: true }
      - { label: "Email", name: "email", widget: "string", required: true }
      - { label: "Phone Number", name: "phone number", widget: "string" }
